# Generated by Django 3.1 on 2020-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'homies'},
        ),
        migrations.AddField(
            model_name='home',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
